apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-events-logger
  namespace: ${NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-events-logger
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-events-logger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-events-logger
subjects:
  - kind: ServiceAccount
    name: k8s-events-logger
    namespace: ${NAMESPACE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-events-logger
  name: k8s-events-logger
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-events-logger
  strategy: {}
  template:
    metadata:
      labels:
        app: k8s-events-logger
    spec:
      serviceAccountName: k8s-events-logger
      containers:
      - image: ${IMAGE}
        name: k8s-events-logger
        resources: {}